---
- name: Create new macOS Vagrant Box
  hosts: localhost
  vars_files:
    - "playbook_vars.yml"
  tasks:
    - name: Create metadata file
      copy:
        src: "/Volumes/Media/Parallels/macOS Vagrant Box/metadata.json.template"
        dest: "/Volumes/Media/Parallels/macOS Vagrant Box/metadata.json"
    - name: Configure metadata file
      replace:
        path: "/Volumes/Media/Parallels/macOS Vagrant Box/metadata.json"
        regexp: 'OS_NAME'
        replace: "{{ macos_name }}"
    - name: Create Vagrant file
      copy:
        src: "/Volumes/Media/Parallels/macOS Vagrant Box/Vagrantfile.template"
        dest: "/Volumes/Media/Parallels/macOS Vagrant Box/Vagrantfile"
    - name: Configure Vagrant file
      replace:
        path: "/Volumes/Media/Parallels/macOS Vagrant Box/Vagrantfile"
        regexp: 'OS_NAME'
        replace: "{{ macos_name }}"
    - name: Copy macOS VM
      copy:
        src: "/Volumes/Media/Parallels/macOS {{ macos_version }}.pvm"
        dest: "/Volumes/Media/Parallels/macOS Vagrant Box"
    - name: Remove unnecessary files from source
      file:
        path: "/Volumes/Media/Parallels/macOS Vagrant Box/macOS {{ macos_version }}.pvm/config.pvs.backup"
        state: absent
    - name: Optimize HDD
      command: "prl_disk_tool compact --hdd '/Volumes/Media/Parallels/macOS Vagrant Box/macOS {{ macos_version }}.pvm/harddisk.hdd'"
    - name: Package VM
      community.general.archive:
        path:
          - "/Volumes/Media/Parallels/macOS Vagrant Box/macos.box"
          - "/Volumes/Media/Parallels/macOS Vagrant Box/macOS {{ macos_version }}.pvm"
          - "/Volumes/Media/Parallels/macOS Vagrant Box/Vagrantfile"
          - "/Volumes/Media/Parallels/macOS Vagrant Box/metadata.json"
        dest: "/Volumes/Media/Parallels/macOS Vagrant Box/macos.box"
    - name: Add new box
      command: "vagrant box add --name scottharwell/macOS-{{ macos_name }} -c -f --machine-readable --provider parallels '/Volumes/Media/Parallels/macOS Vagrant Box/macos.box'"
    - name: Remove macos.box
      file:
        path: "/Volumes/Media/Parallels/macOS Vagrant Box/macos.box"
        state: absent
    - name: Remove copied VM
      file:
        path: "/Volumes/Media/Parallels/macOS Vagrant Box/macOS {{ macos_version }}.pvm"
        state: absent
    - name: Remove metadata file
      file:
        path: "/Volumes/Media/Parallels/macOS Vagrant Box/metadata.json"
        state: absent
    - name: Remove Vagrant file
      file:
        path: "/Volumes/Media/Parallels/macOS Vagrant Box/Vagrantfile"
        state: absent
