---
- name: Create new macOS Vagrant Box
  hosts: localhost
  vars_files:
    - "playbook_vars.yml"
  tasks:
    - name: Create metadata file
      copy:
        src: "{{ playbook_dir }}/metadata.json.template"
        dest: "{{ playbook_dir }}/metadata.json"
    - name: Configure metadata file
      replace:
        path: "{{ playbook_dir }}/metadata.json"
        regexp: 'OS_NAME'
        replace: "{{ macos_name }}"
    - name: Create Vagrant file
      copy:
        src: "{{ playbook_dir }}/Vagrantfile.template"
        dest: "{{ playbook_dir }}/Vagrantfile"
    - name: Configure Vagrant file
      replace:
        path: "{{ playbook_dir }}/Vagrantfile"
        regexp: 'OS_NAME'
        replace: "{{ macos_name }}"
    - name: Copy macOS VM
      copy:
        src: "{{ parallels_path }}/macOS {{ macos_version }}.pvm"
        dest: "{{ playbook_dir }}"
    - name: Remove unnecessary files from source
      file:
        path: "{{ playbook_dir }}/macOS {{ macos_version }}.pvm/config.pvs.backup"
        state: absent
    - name: Optimize HDD
      command: "prl_disk_tool compact --hdd '{{ playbook_dir }}/macOS {{ macos_version }}.pvm/harddisk.hdd'"
    - name: Package VM
      community.general.archive:
        path:
          - "{{ playbook_dir }}/macOS {{ macos_version }}.pvm"
          - "{{ playbook_dir }}/Vagrantfile"
          - "{{ playbook_dir }}/metadata.json"
        dest: "{{ playbook_dir }}/macos.box"
    - name: Add new box
      command: "vagrant box add --name scottharwell/macOS-{{ macos_name }} -c -f --machine-readable --provider parallels '{{ playbook_dir }}/macos.box'"
    - name: Remove macos.box
      file:
        path: "{{ playbook_dir }}/macos.box"
        state: absent
    - name: Remove copied VM
      file:
        path: "{{ playbook_dir }}/macOS {{ macos_version }}.pvm"
        state: absent
    - name: Remove metadata file
      file:
        path: "{{ playbook_dir }}/metadata.json"
        state: absent
    - name: Remove Vagrant file
      file:
        path: "{{ playbook_dir }}/Vagrantfile"
        state: absent
